### ISSUE TITLE
Dll

### ISSUE THREAD

**Issue by ZaarKl** [mentalrob/ChatCommands#6]
Hey, how can we get the ChatCommands.dll because it is not in the installation file you give and i don't think it will work without it . Besides where do i must move your Chatcommands folder ?

**Comment by HornsGuy** [comment]
I am seeing it in ChatCommands.rar
![image](https://user-images.githubusercontent.com/37481699/198479012-6b0c86cf-4e7a-4941-8186-363baffbdab3.png)

**Comment by mentalrob** [comment]
It's located in rar file and rar file is in release page.
