### ISSUE TITLE
Healing command

### ISSUE THREAD

**Issue by Falcomfr** [mentalrob/ChatCommands#9]
Hello,

It would be nice to add a command to heal one player or all players.

Thank you

**Comment by Falcomfr** [comment]
@mentalrob @HornsGuy 
I've create 3 commands, !heal <player name> !healme !healall

Can you give me the rights to create a merge request?

**Comment by mentalrob** [comment]
@Falcomfr you should be able to create PR. Fork the repo apply your changes and create a PR, i will merge it

**Comment by Falcomfr** [comment]
Permission to mentalrob/ChatCommands.git denied to Falcomfr.

**Comment by Falcomfr** [comment]
@mentalrob I failed my PR x) i close and recreate one, i need to push ChatCommands.sln ?

**Comment by mentalrob** [comment]
just push the cs files

**Comment by Falcomfr** [comment]
https://github.com/mentalrob/ChatCommands/pull/11
